let itensNoSupermercado = [
    "Leite",
    "Pão",
    "Arroz",
    "Feijão",
    "Açúcar",
    "Sal",
    "Farinha de trigo",
    "Macarrão",
    "Óleo de cozinha",
    "Manteiga",
    "Margarina",
    "Queijo",
    "Presunto",
    "Frango",
    "Carne bovina",
    "Carne suína",
    "Peixe",
    "Ovos",
    "Alface",
    "Tomate",
    "Cebola",
    "Batata",
    "Cenoura",
    "Pimentão",
    "Alho",
    "Brócolis",
    "Espinafre",
    "Abobrinha",
    "Berinjela",
    "Beterraba",
    "Maçã",
    "Banana",
    "Laranja",
    "Uva",
    "Melancia",
    "Mamão",
    "Morango",
    "Abacaxi",
    "Manga",
    "Limão",
    "Pera",
    "Abacate",
    "Kiwi",
    "Pêssego",
    "Ameixa",
    "Melão",
    "Cereja",
    "Coco",
    "Iogurte",
    "Requeijão"
];
let contador = 0;

while(contador < itensNoSupermercado.length) {
    console.log(itensNoSupermercado[contador]);
    contador++
} 